BiblioCat.WebMVC/Controllers/BookController.cs
using BiblioCat.Models.Book;
using BiblioCat.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioCat.WebMVC.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
            var service = CreateBookService();
            var model = service.GetBooks();

            return View(model);
        }

        public ActionResult Create()
        {
            return View(new BookCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateBookService();

            if (service.CreateBook(model))
            {
                TempData["SaveResult"] = "The book was created.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Book could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var service = CreateBookService();
            var model = service.GetBookById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateBookService();
            var detail = service.GetBookById(id);

            var model = new BookEdit
            {
                BookId = detail.BookId,
                Title = detail.Title,
                PublicationDate = detail.PublicationDate,
                ISBN = detail.ISBN,
                GenreOfBook = detail.GenreOfBook,
                FormatOfBook = detail.FormatOfBook,
                LoanedTo = detail.LoanedTo,
                Narrator = detail.Narrator,
                Translator = detail.Translator,
                Illustrator = detail.Illustrator,
                IsFirstEdition = detail.IsFirstEdition,
                IHaveRead = detail.IHaveRead,
                IOwn = detail.IOwn
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, BookEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.BookId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateBookService();

            if (service.UpdateBook(model))
            {
                TempData["SaveResult"] = "The book was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The book could not be updated.");

            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var service = CreateBookService();
            var model = service.GetBookById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateBookService();
            service.DeleteBook(id);

            TempData["SaveResult"] = "The book was deleted.";

            return RedirectToAction("Index");
        }

        private BookService CreateBookService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new BookService(userId);
            return service;
        }
    }
}

BiblioCat.WebMVC/Controllers/TableJunctions/AuthorBookController.cs
using BiblioCat.Models.TableJunctions.AuthorBook;
using BiblioCat.Services.TableJunctions;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioCat.WebMVC.Controllers.TableJunctions
{
    [Authorize]
    public class AuthorBookController : Controller
    {        
        public ActionResult AddBooks(int id)
        {
            var service = CreateAuthorBookService();
            var authorModel = service.AuthorOptions(id);
            var books = service.GetBooks();
            ViewBag.Books = books;
            ViewData["Authors"] = authorModel;

            return View(new AddBooksCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBooks(AddBooksCreate model)
        {
            var service = CreateAuthorBookService();
                        
            service.AddBook(model);

            return RedirectToAction("Index", "Author");
        }

        public ActionResult AddAuthors(int id)
        {
            var service = CreateAuthorBookService();
            var bookModel = service.BookOptions(id);
            var authors = service.GetAuthors();
            ViewBag.Authors = authors;
            ViewData["Books"] = bookModel;

            return View(new AddAuthorsCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAuthors(AddAuthorsCreate model)
        {
            var service = CreateAuthorBookService();

            service.AddAuthor(model);

            return RedirectToAction("Index", "Book");
        }

        public ActionResult RemoveBooks(int id)
        {
            var service = CreateAuthorBookService();
            var authorModel = service.AuthorOptions(id);
            var books = service.GetBooks();
            ViewBag.Books = books;
            ViewData["Authors"] = authorModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveBooks(AddBooksCreate model)
        {
            var service = CreateAuthorBookService();

            service.RemoveBook(model);

            return RedirectToAction("Index", "Author");
        }

        public ActionResult RemoveAuthors(int id)
        {
            var service = CreateAuthorBookService();
            var bookModel = service.BookOptions(id);
            var authors = service.GetAuthors();
            ViewBag.Authors = authors;
            ViewData["Books"] = bookModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveAuthors(AddAuthorsCreate model)
        {
            var service = CreateAuthorBookService();

            service.RemoveAuthor(model);

            return RedirectToAction("Index", "Book");
        }

        private AuthorBookService CreateAuthorBookService()
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            var service = new AuthorBookService(userId);
            return service;
        }
    }
}

BiblioCat.WebMVC/Controllers/TableJunctions/BookPublisherController.cs
using BiblioCat.Models.TableJunctions.BookPublisher;
using BiblioCat.Services.TableJunctions;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioCat.WebMVC.Controllers.TableJunctions
{
    [Authorize]
    public class BookPublisherController : Controller
    {        
        public ActionResult AddBooks(int id)
        {
            var service = CreateBookPublisherService();
            var books = service.GetBooks();
            var publisherModel = service.PublisherOptions(id);
            ViewBag.Books = books;
            ViewData["Publishers"] = publisherModel;

            return View(new AddBooksCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBooks(AddBooksCreate model)
        {
            var service = CreateBookPublisherService();

            service.AddBook(model);

            return RedirectToAction("Index", "Publisher");
        }

        public ActionResult AddPublishers(int id)
        {
            var service = CreateBookPublisherService();
            var bookModel = service.BookOptions(id);
            var publishers = service.GetPublishers();
            ViewBag.Publishers = publishers;
            ViewData["Books"] = bookModel;

            return View(new AddPublishersCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPublishers(AddPublishersCreate model)
        {
            var service = CreateBookPublisherService();

            service.AddPublisher(model);

            return RedirectToAction("Details", "Book", new { id = model.BookId });
        }

        public ActionResult RemoveBooks(int id)
        {
            var service = CreateBookPublisherService();
            var books = service.GetBooks();
            var publisherModel = service.PublisherOptions(id);
            ViewBag.Books = books;
            ViewData["Publishers"] = publisherModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveBooks(AddBooksCreate model)
        {
            var service = CreateBookPublisherService();

            service.RemoveBook(model);

            return RedirectToAction("Index", "Publisher");
        }

        public ActionResult RemovePublishers(int id)
        {
            var service = CreateBookPublisherService();
            var bookModel = service.BookOptions(id);
            var publishers = service.GetPublishers();
            ViewBag.Publishers = publishers;
            ViewData["Books"] = bookModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemovePublishers(AddPublishersCreate model)
        {
            var service = CreateBookPublisherService();

            service.RemovePublisher(model);

            return RedirectToAction("Details", "Book", new { id = model.BookId });
        }

        private BookPublisherService CreateBookPublisherService()
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            var service = new BookPublisherService(userId);

            return service;
        }
    }
}

BiblioCat.WebMVC/Controllers/TableJunctions/SeriesBookController.cs
using BiblioCat.Models.TableJunctions.SeriesBook;
using BiblioCat.Services.TableJunctions;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioCat.WebMVC.Controllers.TableJunctions
{
    [Authorize]
    public class SeriesBookController : Controller
    {
        public ActionResult AddBooks(int id)
        {
            var service = CreateSeriesBookService();
            var books = service.GetBooks();
            var seriesModel = service.SeriesOptions(id);
            ViewBag.Books = books;
            ViewData["Series"] = seriesModel;

            return View(new AddBooksCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBooks(AddBooksCreate model)
        {
            var service = CreateSeriesBookService();

            service.AddBook(model);

            return RedirectToAction("Index", "Series");
        }

        public ActionResult AddSeries(int id)
        {
            var service = CreateSeriesBookService();
            var bookModel = service.BookOptions(id);
            var series = service.GetSeries();
            ViewBag.Series = series;
            ViewData["Books"] = bookModel;

            return View(new AddSeriesCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddSeries(AddSeriesCreate model)
        {
            var service = CreateSeriesBookService();

            service.AddSeries(model);

            return RedirectToAction("Index", "Book");
        }

        public ActionResult RemoveBooks(int id)
        {
            var service = CreateSeriesBookService();
            var books = service.GetBooks();
            var seriesModel = service.SeriesOptions(id);
            ViewBag.Books = books;
            ViewData["Series"] = seriesModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveBooks(AddBooksCreate model)
        {
            var service = CreateSeriesBookService();

            service.RemoveBook(model);

            return RedirectToAction("Index", "Series");
        }

        public ActionResult RemoveSeries(int id)
        {
            var service = CreateSeriesBookService();
            var bookModel = service.BookOptions(id);
            var series = service.GetSeries();
            ViewBag.Series = series;
            ViewData["Books"] = bookModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveSeries(AddSeriesCreate model)
        {
            var service = CreateSeriesBookService();

            service.RemoveSeries(model);

            return RedirectToAction("Index", "Book");
        }        

        private SeriesBookService CreateSeriesBookService()
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            var service = new SeriesBookService(userId);
            return service;
        }
    }
}

BiblioCat.WebMVC/Views/Book/Create.cshtml
@model BiblioCat.Models.Book.BookCreate
@using BiblioCat.Data

@{
    ViewBag.Title = "Add Book";
}

<h2>Add Book</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PublicationDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PublicationDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PublicationDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GenreOfBook, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(
                model => model.GenreOfBook,
                new SelectList(Enum.GetValues(typeof(BookGenre))),
                "Genre",
                new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GenreOfBook, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FormatOfBook, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(
                model => model.FormatOfBook,
                new SelectList(Enum.GetValues(typeof(BookFormat))),
                "Format",
                new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FormatOfBook, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LoanedTo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LoanedTo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LoanedTo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Narrator, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Narrator, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Narrator, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Translator, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Translator, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Translator, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Illustrator, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Illustrator, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Illustrator, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsFirstEdition, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsFirstEdition)
                @Html.ValidationMessageFor(model => model.IsFirstEdition, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IHaveRead, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IHaveRead)
                @Html.ValidationMessageFor(model => model.IHaveRead, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IOwn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IOwn)
                @Html.ValidationMessageFor(model => model.IOwn, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
            @Html.ActionLink("Back to Book List", "Index", "Book", routeValues: null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BiblioCat.WebMVC/Views/Book/Delete.cshtml
@model BiblioCat.Models.Book.BookDetail

@{
    ViewBag.Title = "Delete Book";
}

<h2>Delete Book</h2>

<h3>Are you sure you want to delete the book @Html.DisplayFor(model => model.Title)?</h3>
<hr />
<div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.BookId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BookId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PublicationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PublicationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ISBN)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ISBN)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GenreOfBook)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GenreOfBook)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FormatOfBook)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FormatOfBook)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LoanedTo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LoanedTo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Narrator)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Narrator)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Translator)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Translator)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Illustrator)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Illustrator)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsFirstEdition)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsFirstEdition)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IHaveRead)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IHaveRead)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IOwn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IOwn)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <div class="col-md-1"></div>
                <input type="submit" value="Delete" class="btn btn-default" />
                @Html.ActionLink("Back to Book List", "Index", "Book", routeValues: null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
            </div>
        }
    </div>
</div>

BiblioCat.WebMVC/Views/Book/Details.cshtml
@model BiblioCat.Models.Book.BookDetail

@{
    ViewBag.Title = "Book Details";
}

<h2>Book Details</h2>
@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}
<div>
    <hr />
    <div class="container">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.BookId)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BookId)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PublicationDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PublicationDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ISBN)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ISBN)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.GenreOfBook)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.GenreOfBook)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FormatOfBook)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FormatOfBook)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LoanedTo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LoanedTo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Narrator)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Narrator)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Translator)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Translator)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Illustrator)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Illustrator)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsFirstEdition)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsFirstEdition)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IHaveRead)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IHaveRead)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IOwn)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IOwn)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.AuthorsOfBook)
                </dt>

                <dd>
                    @foreach (var item in Model.AuthorsOfBook)
                    {
                        <p>@Html.DisplayFor(modelItem => item.LastName),  @Html.DisplayFor(modelItem => item.FirstName)</p>
                    }
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SeriesOfBook)
                </dt>

                <dd>
                    @foreach (var item in Model.SeriesOfBook)
                    {
                        @Html.DisplayFor(modelItem => item.SeriesName) <br />
                    }
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PublishedBy)
                </dt>

                <dd>
                    @foreach (var item in Model.PublishedBy)
                    {
                        @Html.DisplayFor(modelItem => item.PublisherName) <br />
                    }
                </dd>

            </dl>
        </div>
    </div>

    <div class="container">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            @Html.ActionLink("Edit Book", "Edit", "Book", new { id = Model.BookId }, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
            @Html.ActionLink("Delete Book", "Delete", "Book", new { id = Model.BookId }, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
            @Html.ActionLink("Back to Book List", "Index", "Book", routeValues: null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
        </div>
    </div>
    <br />
    <div class="container">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            @Html.ActionLink("Add Authors to Book", "AddAuthors", "AuthorBook", new { id = Model.BookId }, null) |
            @Html.ActionLink("Remove Authors from Book", "RemoveAuthors", "AuthorBook", new { id = Model.BookId }, null) <br />
            @Html.ActionLink("Add Publishers to Book", "AddPublishers", "BookPublisher", new { id = Model.BookId }, null) |
            @Html.ActionLink("Remove Publishers from Book", "RemovePublishers", "BookPublisher", new { id = Model.BookId }, null) <br />
            @Html.ActionLink("Add Series to Book", "AddSeries", "SeriesBook", new { id = Model.BookId }, null) |
            @Html.ActionLink("Remove Series from Book", "RemoveSeries", "SeriesBook", new { id = Model.BookId }, null)
        </div>
    </div>
</div>

BiblioCat.WebMVC/Views/Book/Index.cshtml
@model IEnumerable<BiblioCat.Models.Book.BookListItem>

@{
    ViewBag.Title = "Book List";
}

<h2>Book List</h2>

<p>
    @Html.ActionLink("Add Book", "Create", "Book", null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
</p>
@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}
<table class="table">
    <tr>        
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GenreOfBook)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublicationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuthorsOfBook)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeriesNames)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>            
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GenreOfBook)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublicationDate)
            </td>
            <td>
                @foreach (var itemModel in item.AuthorsOfBook)
                {
                    <p>@Html.DisplayFor(modelItem => itemModel.LastName), @Html.DisplayFor(modelItem => itemModel.FirstName)</p>
                }
            </td>
            <td>
                @foreach (var itemModel in item.SeriesNames)
                {
                    @Html.DisplayFor(modelItem => itemModel.SeriesName)
                    <br />
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.BookId }) |
                @Html.ActionLink("Details", "Details", new { id = item.BookId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.BookId }) <br />
                @Html.ActionLink("Add Authors", "AddAuthors", "AuthorBook", new { id = item.BookId }, null) |
                @Html.ActionLink("Remove Authors", "RemoveAuthors", "AuthorBook", new { id = item.BookId }, null) <br />
                @Html.ActionLink("Add Series", "AddSeries", "SeriesBook", new { id = item.BookId }, null) |
                @Html.ActionLink("Remove Series", "RemoveSeries", "SeriesBook", new { id = item.BookId }, null)
            </td>
        </tr>
    }

</table>