BiblioCat.WebMVC/Controllers/AuthorController.cs
using BiblioCat.Models.Author;
using BiblioCat.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioCat.WebMVC.Controllers
{
    [Authorize]
    public class AuthorController : Controller
    {
        // GET: Author
        public ActionResult Index()
        {
            var service = CreateAuthorService();
            var model = service.GetAuthors();

            return View(model);
        }

        public ActionResult Create()
        {
            return View(new AuthorCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AuthorCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateAuthorService();

            if (service.CreateAuthor(model))
            {
                TempData["SaveResult"] = "The author was created.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Author could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var service = CreateAuthorService();
            var model = service.GetAuthorById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateAuthorService();
            var detail = service.GetAuthorById(id);

            var model =
                new AuthorEdit
                {
                    AuthorId = detail.AuthorId,
                    LastName = detail.LastName,
                    FirstName = detail.FirstName,
                    Patreon = detail.Patreon,
                    OfficialWebsite = detail.OfficialWebsite,
                    AmazonPage = detail.AmazonPage,
                    GoodreadsPage = detail.GoodreadsPage,
                    TwitterHandle = detail.TwitterHandle
                };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, AuthorEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.AuthorId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateAuthorService();

            if(service.UpdateAuthor(model))
            {
                TempData["SaveResult"] = "The author was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The author could not be updated.");

            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var service = CreateAuthorService();
            var model = service.GetAuthorById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateAuthorService();
            service.DeleteAuthor(id);

            TempData["SaveResult"] = "The author was deleted.";

            return RedirectToAction("Index");
        }

        private AuthorService CreateAuthorService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new AuthorService(userId);
            return service;
        }
    }
}

BiblioCat.WebMVC/Controllers/TableJunctions/AuthorBookController.cs
using BiblioCat.Models.TableJunctions.AuthorBook;
using BiblioCat.Services.TableJunctions;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioCat.WebMVC.Controllers.TableJunctions
{
    [Authorize]
    public class AuthorBookController : Controller
    {        
        public ActionResult AddBooks(int id)
        {
            var service = CreateAuthorBookService();
            var authorModel = service.AuthorOptions(id);
            var books = service.GetBooks();
            ViewBag.Books = books;
            ViewData["Authors"] = authorModel;

            return View(new AddBooksCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBooks(AddBooksCreate model)
        {
            var service = CreateAuthorBookService();
                        
            service.AddBook(model);

            return RedirectToAction("Index", "Author");
        }

        public ActionResult AddAuthors(int id)
        {
            var service = CreateAuthorBookService();
            var bookModel = service.BookOptions(id);
            var authors = service.GetAuthors();
            ViewBag.Authors = authors;
            ViewData["Books"] = bookModel;

            return View(new AddAuthorsCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAuthors(AddAuthorsCreate model)
        {
            var service = CreateAuthorBookService();

            service.AddAuthor(model);

            return RedirectToAction("Index", "Book");
        }

        public ActionResult RemoveBooks(int id)
        {
            var service = CreateAuthorBookService();
            var authorModel = service.AuthorOptions(id);
            var books = service.GetBooks();
            ViewBag.Books = books;
            ViewData["Authors"] = authorModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveBooks(AddBooksCreate model)
        {
            var service = CreateAuthorBookService();

            service.RemoveBook(model);

            return RedirectToAction("Index", "Author");
        }

        public ActionResult RemoveAuthors(int id)
        {
            var service = CreateAuthorBookService();
            var bookModel = service.BookOptions(id);
            var authors = service.GetAuthors();
            ViewBag.Authors = authors;
            ViewData["Books"] = bookModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveAuthors(AddAuthorsCreate model)
        {
            var service = CreateAuthorBookService();

            service.RemoveAuthor(model);

            return RedirectToAction("Index", "Book");
        }

        private AuthorBookService CreateAuthorBookService()
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            var service = new AuthorBookService(userId);
            return service;
        }
    }
}

BiblioCat.WebMVC/Controllers/TableJunctions/AuthorConventionController.cs
using BiblioCat.Models.TableJunctions.AuthorConvention;
using BiblioCat.Services.TableJunctions;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioCat.WebMVC.Controllers.TableJunctions
{
    [Authorize]
    public class AuthorConventionController : Controller
    {        
        public ActionResult AddAuthors(int id)
        {
            var service = CreateAuthorConventionService();
            var authors = service.GetAuthors();
            var conventionModel = service.ConventionOptions(id);
            ViewBag.Authors = authors;
            ViewData["Conventions"] = conventionModel;

            return View(new AddAuthorsCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAuthors(AddAuthorsCreate model)
        {
            var service = CreateAuthorConventionService();

            service.AddAuthor(model);

            return RedirectToAction("Index", "Convention");
        }

        public ActionResult AddConventions(int id)
        {
            var service = CreateAuthorConventionService();
            var authorModel = service.AuthorOptions(id);
            var conventions = service.GetConventions();
            ViewBag.Conventions = conventions;
            ViewData["Authors"] = authorModel;

            return View(new AddConventionsCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddConventions(AddConventionsCreate model)
        {
            var service = CreateAuthorConventionService();

            service.AddConvention(model);

            return RedirectToAction("Index", "Author");
        }

        public ActionResult RemoveAuthors(int id)
        {
            var service = CreateAuthorConventionService();
            var authors = service.GetAuthors();
            var conventionModel = service.ConventionOptions(id);
            ViewBag.Authors = authors;
            ViewData["Conventions"] = conventionModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveAuthors(AddAuthorsCreate model)
        {
            var service = CreateAuthorConventionService();

            service.RemoveAuthor(model);

            return RedirectToAction("Index", "Convention");
        }

        public ActionResult RemoveConventions(int id)
        {
            var service = CreateAuthorConventionService();
            var authorModel = service.AuthorOptions(id);
            var conventions = service.GetConventions();
            ViewBag.Conventions = conventions;
            ViewData["Authors"] = authorModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveConventions(AddConventionsCreate model)
        {
            var service = CreateAuthorConventionService();

            service.RemoveConvention(model);

            return RedirectToAction("Index", "Author");
        }
        
        private AuthorConventionService CreateAuthorConventionService()
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            var service = new AuthorConventionService(userId);
            return service;
        }
    }
}

BiblioCat.WebMVC/Controllers/TableJunctions/AuthorPublisherController.cs
using BiblioCat.Models.TableJunctions.AuthorPublisher;
using BiblioCat.Services.TableJunctions;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioCat.WebMVC.Controllers.TableJunctions
{
    [Authorize]
    public class AuthorPublisherController : Controller
    {
        public ActionResult AddAuthors(int id)
        {
            var service = CreateAuthorPublisherService();
            var authors = service.GetAuthors();
            var publisherModel = service.PublisherOptions(id);
            ViewBag.Authors = authors;
            ViewData["Publishers"] = publisherModel;

            return View(new AddAuthorsCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAuthors(AddAuthorsCreate model)
        {
            var service = CreateAuthorPublisherService();

            service.AddAuthor(model);

            return RedirectToAction("Index", "Publisher");
        }

        public ActionResult AddPublishers(int id)
        {
            var service = CreateAuthorPublisherService();
            var authorModel = service.AuthorOptions(id);
            var publishers = service.GetPublishers();
            ViewBag.Publishers = publishers;
            ViewData["Authors"] = authorModel;

            return View(new AddPublishersCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPublishers(AddPublishersCreate model)
        {
            var service = CreateAuthorPublisherService();

            service.AddPublisher(model);

            return RedirectToAction("Details", "Author", new { id = model.AuthorId });
        }

        public ActionResult RemoveAuthors(int id)
        {
            var service = CreateAuthorPublisherService();
            var authors = service.GetAuthors();
            var publisherModel = service.PublisherOptions(id);
            ViewBag.Authors = authors;
            ViewData["Publishers"] = publisherModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveAuthors(AddAuthorsCreate model)
        {
            var service = CreateAuthorPublisherService();

            service.RemoveAuthor(model);

            return RedirectToAction("Index", "Publisher");
        }

        public ActionResult RemovePublishers(int id)
        {
            var service = CreateAuthorPublisherService();
            var authorModel = service.AuthorOptions(id);
            var publishers = service.GetPublishers();
            ViewBag.Publishers = publishers;
            ViewData["Authors"] = authorModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemovePublishers(AddPublishersCreate model)
        {
            var service = CreateAuthorPublisherService();

            service.RemovePublisher(model);

            return RedirectToAction("Details", "Author", new { id = model.AuthorId });
        }

        private AuthorPublisherService CreateAuthorPublisherService()
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            var service = new AuthorPublisherService(userId);

            return service;
        }
    }
}

BiblioCat.WebMVC/Controllers/TableJunctions/SeriesAuthorController.cs
using BiblioCat.Models.TableJunctions.SeriesAuthor;
using BiblioCat.Services.TableJunctions;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioCat.WebMVC.Controllers.TableJunctions
{
    [Authorize]
    public class SeriesAuthorController : Controller
    {
        public ActionResult AddAuthors(int id)
        {
            var service = CreateSeriesAuthorService();
            var authors = service.GetAuthors();
            var seriesModel = service.SeriesOptions(id);
            ViewBag.Authors = authors;
            ViewData["Series"] = seriesModel;

            return View(new AddAuthorsCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAuthors(AddAuthorsCreate model)
        {
            var service = CreateSeriesAuthorService();

            service.AddAuthor(model);

            return RedirectToAction("Index", "Series");
        }

        public ActionResult AddSeries(int id)
        {
            var service = CreateSeriesAuthorService();
            var authorModel = service.AuthorOptions(id);
            var series = service.GetSeries();
            ViewBag.Series = series;
            ViewData["Authors"] = authorModel;

            return View(new AddSeriesCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddSeries(AddSeriesCreate model)
        {
            var service = CreateSeriesAuthorService();

            service.AddSeries(model);

            return RedirectToAction("Index", "Author");
        }

        public ActionResult RemoveAuthors(int id)
        {
            var service = CreateSeriesAuthorService();
            var authors = service.GetAuthors();
            var seriesModel = service.SeriesOptions(id);
            ViewBag.Authors = authors;
            ViewData["Series"] = seriesModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveAuthors(AddAuthorsCreate model)
        {
            var service = CreateSeriesAuthorService();

            service.RemoveAuthor(model);

            return RedirectToAction("Index", "Series");
        }

        public ActionResult RemoveSeries(int id)
        {
            var service = CreateSeriesAuthorService();
            var authorModel = service.AuthorOptions(id);
            var series = service.GetSeries();
            ViewBag.Series = series;
            ViewData["Authors"] = authorModel;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveSeries(AddSeriesCreate model)
        {
            var service = CreateSeriesAuthorService();

            service.RemoveSeries(model);

            return RedirectToAction("Index", "Author");
        }

        private SeriesAuthorService CreateSeriesAuthorService()
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            var service = new SeriesAuthorService(userId);
            return service;
        }
    }
}

BiblioCat.WebMVC/Views/Author/Create.cshtml
@model BiblioCat.Models.Author.AuthorCreate

@{
    ViewBag.Title = "Add Author";
}

<h2>Add Author</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Patreon, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Patreon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Patreon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OfficialWebsite, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OfficialWebsite, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OfficialWebsite, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AmazonPage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AmazonPage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AmazonPage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GoodreadsPage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GoodreadsPage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GoodreadsPage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TwitterHandle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TwitterHandle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TwitterHandle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
            @Html.ActionLink("Back to Author List", "Index", "Author", routeValues: null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BiblioCat.WebMVC/Views/Author/Delete.cshtml
@model BiblioCat.Models.Author.AuthorDetail

@{
    ViewBag.Title = "Delete Author";
}

<h2>Delete Author</h2>

<h3>Are you sure you want to delete author @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)?</h3>
<hr />
<div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.AuthorId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AuthorId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Patreon)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Patreon)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OfficialWebsite)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OfficialWebsite)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AmazonPage)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AmazonPage)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GoodreadsPage)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GoodreadsPage)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TwitterHandle)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TwitterHandle)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <div class="col-md-1"></div>
                <input type="submit" value="Delete" class="btn btn-default" />
                @Html.ActionLink("Back to Author List", "Index", "Author", routeValues: null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
            </div>
        }
    </div>
</div>

BiblioCat.WebMVC/Views/Author/Details.cshtml
@model BiblioCat.Models.Author.AuthorDetail

@{
    ViewBag.Title = "Author Details";
}

<h2>Author Detail</h2>

<hr />
<div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.AuthorId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AuthorId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Patreon)
            </dt>

            <dd>
                <a href="@Html.DisplayFor(model => model.Patreon)" target="_blank">@Html.DisplayFor(model => model.Patreon)</a>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OfficialWebsite)
            </dt>

            <dd>
                <a href="@Html.DisplayFor(model => model.OfficialWebsite)" target="_blank">@Html.DisplayFor(model => model.OfficialWebsite)</a>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AmazonPage)
            </dt>

            <dd>
                <a href="@Html.DisplayFor(model => model.AmazonPage)" target="_blank">@Html.DisplayFor(model => model.AmazonPage)</a>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GoodreadsPage)
            </dt>

            <dd>
                <a href="@Html.DisplayFor(model => model.GoodreadsPage)" target="_blank">@Html.DisplayFor(model => model.GoodreadsPage)</a>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TwitterHandle)
            </dt>

            <dd>
                <a href="@Html.DisplayFor(model => model.TwitterHandle)" target="_blank">@Html.DisplayFor(model => model.TwitterHandle)</a>
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.BooksByAuthor)
            </dt>
            <dd>
                @foreach (var item in Model.BooksByAuthor)
                {
                    @Html.DisplayFor(modelItem => item.Title) <br />
                }
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.SeriesWritten)
            </dt>
            <dd>
                @foreach (var item in Model.SeriesWritten)
                {
                    @Html.DisplayFor(modelItem => item.SeriesName) <br />
                }
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PublishedBy)
            </dt>
            <dd>
                @foreach (var item in Model.PublishedBy)
                {
                    @Html.DisplayFor(modelItem => item.PublisherName) <br />
                }
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ConventionsAttending)
            </dt>
            <dd>
                @foreach (var item in Model.ConventionsAttending)
                {
                    @Html.DisplayFor(modelItem => item.Name) <br />
                }
            </dd>
        </dl>
    </div>
</div>

<div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="form-actions no-color">
            @Html.ActionLink("Edit Author", "Edit", "Author", new { id = Model.AuthorId }, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
            @Html.ActionLink("Delete Author", "Delete", "Author", routeValues: new { id = Model.AuthorId }, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
            @Html.ActionLink("Back to Author List", "Index", "Author", routeValues: null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
        </div>
    </div>
    <br />
</div>
<br />
<div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        @Html.ActionLink("Add Books to Author", "AddBooks", "AuthorBook", new { id = Model.AuthorId }, null) |
        @Html.ActionLink("Remove Books from Author", "RemoveBooks", "AuthorBook", new { id = Model.AuthorId }, null) <br />
        @Html.ActionLink("Add Conventions to Author", "AddConventions", "AuthorConvention", new { id = Model.AuthorId }, null) |
        @Html.ActionLink("Remove Conventions from Author", "RemoveConventions", "AuthorConvention", new { id = Model.AuthorId }, null) <br />
        @Html.ActionLink("Add Publishers to Author", "AddPublishers", "AuthorPublisher", new { id = Model.AuthorId }, null) |
        @Html.ActionLink("Remove Publishers from Author", "RemovePublishers", "AuthorPublisher", new { id = Model.AuthorId }, null) <br />
        @Html.ActionLink("Add Series to Author", "AddSeries", "SeriesAuthor", new { id = Model.AuthorId }, null) |
        @Html.ActionLink("Remove Series from Author", "RemoveSeries", "SeriesAuthor", new { id = Model.AuthorId }, null)
    </div>
</div>

BiblioCat.WebMVC/Views/Author/Index.cshtml
@model IEnumerable<BiblioCat.Models.Author.AuthorListItem>

@{
    ViewBag.Title = "Author List";
}

<h2>Author List</h2>

<p>
    @Html.ActionLink("Add Author", "Create", "Author", null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
</p>
@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}
<table class="table">
    <tr>        
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookTitles)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeriesNames)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConventionsAttending)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>            
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @foreach (var itemModel in item.BookTitles)
                {
                    @Html.DisplayFor(modelItem => itemModel.Title)
                    <br />
                }
            </td>
            <td>
                @foreach (var itemModel in item.SeriesNames)
                {
                    @Html.DisplayFor(modelItem => itemModel.SeriesName)
                    <br />
                }
            </td>
            <td>
                @foreach (var itemModel in item.ConventionsAttending)
                {
                    @Html.DisplayFor(modelItem => itemModel.Name)
                    <br />
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.AuthorId }) |
                @Html.ActionLink("Details", "Details", new { id = item.AuthorId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.AuthorId }) <br />
                @Html.ActionLink("Add Books", "AddBooks", "AuthorBook", new { id = item.AuthorId }, null) |
                @Html.ActionLink("Remove Books", "RemoveBooks", "AuthorBook", new { id = item.AuthorId }, null) <br />
                @Html.ActionLink("Add Conventions", "AddConventions", "AuthorConvention", new { id = item.AuthorId }, null) |
                @Html.ActionLink("Remove Conventions", "RemoveConventions", "AuthorConvention", new { id = item.AuthorId }, null) <br />
                @Html.ActionLink("Add Series", "AddSeries", "SeriesAuthor", new { id = item.AuthorId }, null) |
                @Html.ActionLink("Remove Series", "RemoveSeries", "SeriesAuthor", new { id = item.AuthorId }, null)
            </td>
        </tr>
    }

</table>